server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: campus-trading-platform
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_trading?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 230528
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
  
  # ElasticSearch配置
  elasticsearch:
    rest:
      uris: http://localhost:9200
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# JWT配置
jwt:
  secret: campus-trading-platform-secret-key
  expiration: 86400000 # 24小时

# 自定义配置
app:
  # 文件存储路径
  file:
    upload-dir: ./uploads
  
  # AI模型配置
  ai:
    model-path: ./models/image-description-model

# 日志配置
logging:
  level:
    root: info
    com.campus.trading: debug
  file:
    name: ./logs/campus-trading.log

sql:
  init:
    mode: always
    data-locations: classpath:db/init.sql 