server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: campus-trading-platform
  
  # 数据库配置 - 请修改为你自己的数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_trading?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 你的密码
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update  # 首次运行可设为create，之后改为update
    properties:
      hibernate:
        format_sql: true
  
  # Redis配置 - 如果没有Redis可以注释掉或配置为禁用
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  
  # RabbitMQ配置 - 如果没有RabbitMQ可以注释掉或配置为禁用
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
  
  # ElasticSearch配置 - 如果没有ElasticSearch可以注释掉或配置为禁用
  elasticsearch:
    rest:
      uris: http://localhost:9200
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # MongoDB配置
  data:
    mongodb:
      host: localhost
      port: 27017
      database: campus_trading
      username:
      password:
      authentication-database: admin

# JWT配置
jwt:
  secret: campus-trading-platform-secret-key  # 生产环境应该使用更复杂的密钥
  expiration: 86400000 # 24小时

# 自定义配置
app:
  # 文件存储路径 - 根据你的环境修改
  file:
    upload-dir: ./uploads
  
  # AI模型配置 - 可选功能
  ai:
    model-path: ./models/image-description-model

  # 腾讯云配置
  tencentcloud:
    secret-id: 你的SecretId
    secret-key: 你的SecretKey
    region: ap-shanghai

  # DeepSeek配置
  deepseek:
    api-key: 你的deepseek_api_key
    base-url: https://api.deepseek.com


# 日志配置
logging:
  level:
    root: info
    com.campus.trading: debug
  file:
    name: ./logs/campus-trading.log

# 图片存储相关配置
image:
  bucket: images
  url-prefix: /api/image/ 